/**
 * ResQ Decision Intelligence Engine V3.1 — Independent Holdout Benchmark Registry
 * 
 * Strict Principle:
 * These holdout locations were NOT used during engine calibration or threshold tuning.
 * Evaluates generalizability across diverse multi-hazard physiographic regions of India.
 */

import type { ValidationBenchmark } from "./calibrationRegistry";

export const HOLDOUT_BENCHMARKS: ValidationBenchmark[] = [
  {
    id: "HOL-UK-UTK",
    name: "Uttarkashi",
    stateCode: "UK",
    latitude: 30.7268,
    longitude: 78.4354,
    slopeDegrees: 32,
    elevationMeters: 1158,
    groundTruthPrimaryHazard: ["LANDSLIDE", "SEISMIC"],
    groundTruthTiers: ["RED"],
    groundTruthSource: "BIS IS 1893:2016 Zone V; GSI Mass Movement Inventory; 2013 Bhagirathi deluge records",
    groundTruthStatus: "VERIFIED",
    notes: "High Himalayan tectonic belt; steep Bhagirathi valley slope >30°; BIS Zone V regulatory baseline",
  },
  {
    id: "HOL-AS-DHE",
    name: "Dhemaji",
    stateCode: "AS",
    latitude: 27.4800,
    longitude: 94.5800,
    slopeDegrees: 1,
    elevationMeters: 91,
    groundTruthPrimaryHazard: ["FLOOD", "RIVERBANK_EROSION"],
    groundTruthTiers: ["RED", "ORANGE"],
    groundTruthSource: "CWC Jiabharali / Dhemaji Crossing (CWC-AS-DHE); Brahmaputra Board north bank inundation records",
    groundTruthStatus: "VERIFIED",
    notes: "Brahmaputra north bank recurrent flash-flood and river avulsion zone",
  },
  {
    id: "HOL-KL-IDK",
    name: "Idukki",
    stateCode: "KL",
    latitude: 10.1558,
    longitude: 77.0142,
    slopeDegrees: 30,
    elevationMeters: 1200,
    groundTruthPrimaryHazard: ["LANDSLIDE"],
    groundTruthTiers: ["RED", "ORANGE"],
    groundTruthSource: "ISRO Landslide Atlas 2023 (Rank #18/147); 2020 Pettimudi landslide event (66 fatalities)",
    groundTruthStatus: "VERIFIED",
    notes: "Western Ghats steep scarp terrain; ISRO high susceptibility ranking #18; Pettimudi debris flow ground zero",
  },
  {
    id: "HOL-OD-KEN",
    name: "Kendrapara",
    stateCode: "OD",
    latitude: 20.5000,
    longitude: 86.4200,
    slopeDegrees: 1,
    elevationMeters: 7,
    groundTruthPrimaryHazard: ["CYCLONE", "FLOOD"],
    groundTruthTiers: ["ORANGE", "RED"],
    groundTruthSource: "CWC Indupur gauge (CWC-OD-KEN); IMD Historical Cyclone Landfall Records (1999 Super Cyclone corridor)",
    groundTruthStatus: "VERIFIED",
    notes: "Low-elevation deltaic coastal plain subject to Brahmani-Baitarani flooding and Bay of Bengal storm surges",
  },
  {
    id: "HOL-AP-VIJ",
    name: "Vijayawada",
    stateCode: "AP",
    latitude: 16.5080,
    longitude: 80.6050,
    slopeDegrees: 2,
    elevationMeters: 19,
    groundTruthPrimaryHazard: ["FLOOD", "CYCLONE"],
    groundTruthTiers: ["ORANGE", "RED"],
    groundTruthSource: "CWC Prakasam Barrage station (CWC-AP-VIJ); APSDMA flood hazard mapping",
    groundTruthStatus: "VERIFIED",
    notes: "Lower Krishna River basin; downstream of Prakasam Barrage flood discharge corridor",
  },
  {
    id: "HOL-WB-HGL",
    name: "Arambagh",
    stateCode: "WB",
    latitude: 22.8800,
    longitude: 87.7800,
    slopeDegrees: 1,
    elevationMeters: 15,
    groundTruthPrimaryHazard: ["FLOOD"],
    groundTruthTiers: ["ORANGE", "RED"],
    groundTruthSource: "CWC Middle Ganga / Damodar Valley Corporation flood records; West Bengal Disaster Management Department",
    groundTruthStatus: "VERIFIED",
    notes: "Damodar–Dwarakeswar spill basin; recurrent monsoon inundation following DVC dam discharges",
  },
  {
    id: "HOL-MH-KOL",
    name: "Kolhapur",
    stateCode: "MH",
    latitude: 16.7000,
    longitude: 74.2400,
    slopeDegrees: 2,
    elevationMeters: 540,
    groundTruthPrimaryHazard: ["FLOOD"],
    groundTruthTiers: ["ORANGE", "RED"],
    groundTruthSource: "CWC Upper Krishna Division; Panchganga River 2019/2021 flood high-water marks",
    groundTruthStatus: "VERIFIED",
    notes: "Panchganga-Krishna confluence flood basin; severe 2019 inundation affecting 150+ taluka villages",
  },
  {
    id: "HOL-CT-RAI",
    name: "Raipur",
    stateCode: "CT",
    latitude: 21.2514,
    longitude: 81.6296,
    slopeDegrees: 1,
    elevationMeters: 298,
    groundTruthPrimaryHazard: ["DROUGHT", "EXTREME_HEAT", "FLOOD"],
    groundTruthTiers: ["GREEN", "ORANGE"],
    groundTruthSource: "BIS IS 1893:2016 Zone II; IMD Climatological Normals; CGSDMA Baseline",
    groundTruthStatus: "VERIFIED",
    notes: "Central Peninsular stable craton; low seismic risk (Zone II); absence of active flood or landslide triggers",
  },
  {
    id: "HOL-MP-IND",
    name: "Indore",
    stateCode: "MP",
    latitude: 22.7196,
    longitude: 75.8577,
    slopeDegrees: 2,
    elevationMeters: 553,
    groundTruthPrimaryHazard: ["DROUGHT", "EXTREME_HEAT", "FLOOD"],
    groundTruthTiers: ["GREEN", "ORANGE"],
    groundTruthSource: "BIS IS 1893:2016 Zone II; IMD Meteorological Data; MP SDMA Baseline",
    groundTruthStatus: "VERIFIED",
    notes: "Malwa Plateau stable Deccan basalt; BIS Seismic Zone II; standard baseline conditions",
  },
  {
    id: "HOL-MZ-LUN",
    name: "Lunglei",
    stateCode: "MZ",
    latitude: 22.8800,
    longitude: 92.7300,
    slopeDegrees: 26,
    elevationMeters: 1020,
    groundTruthPrimaryHazard: ["LANDSLIDE", "SEISMIC"],
    groundTruthTiers: ["RED", "ORANGE"],
    groundTruthSource: "ISRO Landslide Atlas 2023 (Rank #11/147); BIS IS 1893:2016 Zone V",
    groundTruthStatus: "VERIFIED",
    notes: "Steep anticlinal ridges in Indo-Burma tectonic wedge; ISRO Rank #11; BIS Zone V",
  },
];
