import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import type { IndiaLocation } from "@shared/india";
import { Loader2, MapPin, Search } from "lucide-react";
import { useState } from "react";

export function IndiaLocationSearch({ onSelect, tone = "light" }: { onSelect: (location: IndiaLocation) => void; tone?: "light" | "dark" }) {
  const [query, setQuery] = useState("");
  const results = trpc.diva.india.search.useQuery({ query }, { enabled: query.trim().length >= 2, staleTime: 15 * 60 * 1000 });
  const dark = tone === "dark";
  return <div className="relative z-30 w-full"><Search className={`pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 ${dark ? "text-[#8faab1]" : "text-[#6f8791]"}`} /><Input data-testid="india-location-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search India: state, city, district, locality" className={dark ? "h-10 rounded-xl border-[#3c5964] bg-[#0c2029]/95 pl-9 pr-8 text-sm text-[#e7f5f6] shadow-2xl placeholder:text-[#8ca4ab] focus-visible:ring-[#66be83]" : "h-10 rounded-xl border-[#cfe0e4] bg-white pl-9 pr-8 text-sm shadow-sm focus-visible:ring-[#31879b]"} aria-label="Search Indian locations" />{results.isFetching && <Loader2 className={`absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 animate-spin ${dark ? "text-[#78ca83]" : "text-[#328397]"}`} />}{query.trim().length >= 2 && <div data-testid="india-location-results" className={`absolute top-11 w-full overflow-hidden rounded-xl p-1.5 shadow-2xl ${dark ? "border border-[#3c5964] bg-[#0b1d26]" : "border border-[#d7e4e7] bg-white"}`}>{results.isLoading ? <p className={`px-3 py-3 text-xs ${dark ? "text-[#9eb4ba]" : "text-[#6f8490]"}`}>Searching India…</p> : results.data?.length ? results.data.map(item => <button data-testid="india-location-result" key={item.id} onClick={() => { onSelect(item); setQuery(""); }} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left ${dark ? "hover:bg-[#15333d]" : "hover:bg-[#edf7f8]"}`}><span className={`grid h-7 w-7 place-items-center rounded-lg ${dark ? "bg-[#173b39] text-[#79cf87]" : "bg-[#e9f5f6] text-[#1e778a]"}`}><MapPin className="h-3.5 w-3.5" /></span><span className="min-w-0"><span className={`block truncate text-xs font-bold ${dark ? "text-[#e6f6f1]" : "text-[#274d60]"}`}>{item.name}</span><span className={`block truncate text-[10px] ${dark ? "text-[#91aab1]" : "text-[#718690]"}`}>{item.category} · {item.displayName}</span></span></button>) : <p className={`px-3 py-3 text-xs ${dark ? "text-[#9eb4ba]" : "text-[#6f8490]"}`}>No matching Indian location was found.</p>}</div>}</div>;
}
